@hostname = http://localhost:9000

get {{hostname}}/api/user/login

###

post {{hostname}}/api/user/login
Content-Type: application/json

{
    "email": "youu@gmail.com",
    "password": "Abcabc123!"
}

###

post {{hostname}}/api/user/signup
Content-Type: application/json

{
    "email": "youu@gmail.com",
    "password": "Abcabc123!"
}