@hostname = http://localhost:9000

get {{hostname}}/api/post
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2Q4ZmZkYWUyZDU4ODNiZjdmYjYyYzkiLCJpYXQiOjE2NzUxNjkyNjgsImV4cCI6MTY3NTI1NTY2OH0.smBWmAUwDvGxV2D45zMOTnKHUOWge2L_ICFE6GVgDQw

###

post {{hostname}}/api/comment
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2Q4ZmZkYWUyZDU4ODNiZjdmYjYyYzkiLCJpYXQiOjE2NzUxNjkyNjgsImV4cCI6MTY3NTI1NTY2OH0.smBWmAUwDvGxV2D45zMOTnKHUOWge2L_ICFE6GVgDQw

{
    "name": "John Doe",
    "message": "Welcome back haha"
}

###

delete {{hostname}}/api/post/id

###

patch {{hostname}}/api/post/id
Content-Type: application/json

{
    "message": "Good morning"
}

###

post {{hostname}}/api/user/login
Content-Type: application/json

{
    "email": "youl@gmail.com",
    "password": "Abcabc123!"
}

###

post {{hostname}}/api/user/signup
Content-Type: application/json

{
    "name": "Apple",
    "email": "yin@gmail.com",
    "password": "Abcabc123!"
}