import style from "@/styles/friendlist.module.scss";

export default function FriendList() {
    return (
        <div className={style.friend_list}>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
        </div>
    );
}
