import style from "@/styles/postcontainer.module.scss";

export default function PostContainer() {
    return (
        <div className={style.post_container}>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
            <div>PostContainer</div>
        </div>
    );
}
