import style from "@/styles/sidenav.module.scss";

export default function SideNav() {
    return (
        <div className={style.nav}>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
            <div>SideNav</div>
        </div>
    );
}
